// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVx4MBWOumLBwb9J0klEkeyMNz4NEGw54',
    appId: '1:631275381670:web:58600a33dc37dc5dcfa567',
    messagingSenderId: '631275381670',
    projectId: 'knowyoirguide',
    authDomain: 'knowyoirguide.firebaseapp.com',
    storageBucket: 'knowyoirguide.firebasestorage.app',
    measurementId: 'G-J11T19JDPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnPgG54f7_VeGb9dSWG2FXLlQuFaC-CA',
    appId: '1:631275381670:android:c6075bcf3cbb0798cfa567',
    messagingSenderId: '631275381670',
    projectId: 'knowyoirguide',
    storageBucket: 'knowyoirguide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApae_VYb_4xH4g85sIgXgLKoJu4ALKf8Y',
    appId: '1:631275381670:ios:e8b9a6aa51945e09cfa567',
    messagingSenderId: '631275381670',
    projectId: 'knowyoirguide',
    storageBucket: 'knowyoirguide.firebasestorage.app',
    iosClientId: '631275381670-55rtg83m05cc9bkai47u2lfr5uhrkoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowYourGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApae_VYb_4xH4g85sIgXgLKoJu4ALKf8Y',
    appId: '1:631275381670:ios:e8b9a6aa51945e09cfa567',
    messagingSenderId: '631275381670',
    projectId: 'knowyoirguide',
    storageBucket: 'knowyoirguide.firebasestorage.app',
    iosClientId: '631275381670-55rtg83m05cc9bkai47u2lfr5uhrkoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowYourGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVx4MBWOumLBwb9J0klEkeyMNz4NEGw54',
    appId: '1:631275381670:web:91dc06b201d793cacfa567',
    messagingSenderId: '631275381670',
    projectId: 'knowyoirguide',
    authDomain: 'knowyoirguide.firebaseapp.com',
    storageBucket: 'knowyoirguide.firebasestorage.app',
    measurementId: 'G-8KY61SPJ21',
  );
}
